package db.entity;
// Generated 2015-12-15 23:14:26 by Hibernate Tools 4.3.1.Final

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private String cno;
	private String cname;

	public Course() {
	}

	public Course(String cno, String cname) {
		this.cno = cno;
		this.cname = cname;
	}

	public String getCno() {
		return this.cno;
	}

	public void setCno(String cno) {
		this.cno = cno;
	}

	public String getCname() {
		return this.cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

}
