package db.entity;
// Generated 2015-12-16 20:34:33 by Hibernate Tools 4.3.1.Final

/**
 * Sc generated by hbm2java
 */
public class Sc implements java.io.Serializable {

	private ScId id;
	private String tno;
	private Integer absenceNum;

	public Sc() {
	}

	public Sc(ScId id, String tno) {
		this.id = id;
		this.tno = tno;
	}

	public Sc(ScId id, String tno, Integer absenceNum) {
		this.id = id;
		this.tno = tno;
		this.absenceNum = absenceNum;
	}

	public ScId getId() {
		return this.id;
	}

	public void setId(ScId id) {
		this.id = id;
	}

	public String getTno() {
		return this.tno;
	}

	public void setTno(String tno) {
		this.tno = tno;
	}

	public Integer getAbsenceNum() {
		return this.absenceNum;
	}

	public void setAbsenceNum(Integer absenceNum) {
		this.absenceNum = absenceNum;
	}

}
