package db.entity;
// Generated 2015-12-16 20:34:33 by Hibernate Tools 4.3.1.Final

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private String sno;
	private String sname;
	private String spwd;

	public Student() {
	}

	public Student(String sno, String sname, String spwd) {
		this.sno = sno;
		this.sname = sname;
		this.spwd = spwd;
	}

	public String getSno() {
		return this.sno;
	}

	public void setSno(String sno) {
		this.sno = sno;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public String getSpwd() {
		return this.spwd;
	}

	public void setSpwd(String spwd) {
		this.spwd = spwd;
	}

}
